version: "3.12"

services:
  web: &web
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data1/
    env_file:
      - .envs/.local/.postgres

#  redis:
#    image: redis
#    container_name: redis-container
#    ports:
#      - "6379:6379"
#  worker:
#    <<: *web
#    command: celery --app=config worker --loglevel=info
#    links:
#      - redis
#    ports: []
#    depends_on:
#      - api
#      - redis
#  beat:
#    <<: *web
#    command: celery --app=config beat --loglevel=info
#    ports: []
#    depends_on:
#      - web
#      - redis

volumes:
  postgres_data: {}